version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: container_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: maxmilhas
    ports:
      - "9999:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
